name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: yuumi-rs
      - uses: actions/checkout@v4
        with:
          repository: YuumiConnectionLibrary/yuumi-spec
          path: yuumi-spec
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
        working-directory: yuumi-rs
      - run: cargo test --all-targets
        working-directory: yuumi-rs
